#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fogg_efs="0.0.1"
  jq -n --arg fogg_efs "$ver_fogg_efs" '{fogg_efs: $fogg_efs}'
}

version "$@"
